# Generated by Django 2.2.3 on 2019-08-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parier', '0002_remove_formule_prenoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('sex', models.CharField(max_length=10)),
                ('localisation', models.CharField(max_length=42)),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
    ]
